# Netlify Build Settings
[build]
  # This command should match the one in your Netlify UI settings
  # command = "npm run build" 

  # This publish directory MUST match the one in your Netlify UI settings.
  # Since your base directory is 'frontend', this should be 'frontend/dist'.
  publish = "frontend/dist" 

# Redirect rule for Single Page Applications (SPA)
[[redirects]]
  # Redirect all paths...
  from = "/*" 
  # ...to the main index.html file in the publish directory.
  to = "/index.html" 
  # Return a 200 status code to let the client-side router handle it.
  status = 200